name: monk
description: Monk

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aes_crypt: ^0.1.1
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  webview_flutter: 1.0.3
  shared_preferences: "0.5.12+2"
  encrypt: "4.1.0"
  flutter_secure_storage: "3.3.5"
  material_design_icons_flutter: 4.0.5755
  badges: ^1.1.3
  flutter_launcher_icons: "^0.7.0"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  custom_splash: ^0.0.2
  charts_flutter: ^0.9.0
  flutter_app_lock: ^1.4.0
  #todo mit nächstem release kann local_auth das ohne die untere dep local_auth: ^0.6.3+3
  local_auth_device_credentials: ^0.6.3+10
  flutter_material_color_picker: ^1.0.3
  smart_select: ^4.3.2
  date_time_picker: ^1.0.2
  flutter_svg: ^0.19.1
  flutter_pdfview: ^1.0.4
  flutter_local_notifications: ^3.0.3
  http: ^0.12.2
  flutter_chips_input: ^1.9.4
  csv: ^4.1.0
  carousel_slider: ^2.3.1
  provider: ^4.3.2
  pdf: ^2.0.0
  permission_handler: ^5.0.1+1
  path: ^1.7.0
  path_provider: ^1.6.24
  photo_view: ^0.10.3
  pointycastle: ^2.0.0
  native_pdf_renderer: any
  native_pdf_view: ^3.8.0
  share: ^0.6.5+4
  sortedmap: ^0.4.2+1
  numberpicker: ^1.3.0
  flutter_typeahead: ^1.8.8
  bitmap: ^0.0.6
  image: ^2.1.19
  flutter_tags: ^0.1.9
  file_picker: ^2.1.4
  uuid: ^2.2.2
  camera: ^0.6.0
  url_launcher: ^5.7.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^0.6.3


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/combined.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/res/modules/
    - assets/res/pool/
    - assets/icons/pool/
    - assets/icons/pool/medication/
    - assets/icons/pool/daytime/
    - assets/icons/monkicon.png
    - assets/icons/monkicon_with_text.png
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png

  #To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
