name: monk
description: Monk

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aes_crypt: ^0.1.1
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  webview_flutter: 2.0.2
  shared_preferences: 2.0.5
  encrypt:  5.0.0-beta.1
  flutter_secure_storage: 4.1.0
  material_design_icons_flutter: 5.0.5955-rc.1
  badges: ^2.0.0-nullsafety.1
  charts_flutter: ^0.11.0
  flutter_app_lock: ^2.0.0
  local_auth: ^1.1.0
  image_picker: ^0.7.3
  flutter_material_color_picker: ^1.0.3
  date_time_picker: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_pdfview: ^1.0.4
  flutter_local_notifications: ^5.0.0-nullsafety.1
  http: ^0.13.0
  csv: ^5.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  provider: ^5.0.0
  pdf: ^3.0.1
  permission_handler: ^6.1.1
  path: ^1.7.0
  path_provider: ^2.0.1
  photo_view: ^0.11.1
  pointycastle: ^3.0.0-nullsafety.0
  native_pdf_renderer: any
  share: ^2.0.1
  sortedmap: ^0.5.0-nullsafety.0
  numberpicker: ^2.0.1
  flutter_typeahead: ^3.0.0-nullsafety.0
  bitmap: ^0.1.2
  image: ^3.0.1
  file_picker: ^3.0.0
  uuid: ^3.0.1
  camera: ^0.8.0
  url_launcher: ^6.0.2
  flutter_full_pdf_viewer: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^1.0.0


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/combined.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/res/modules/
    - assets/res/pool/
    - assets/examples/
    - assets/icons/pool/
    - assets/icons/pool/medication/
    - assets/icons/pool/daytime/
    - assets/icons/monkicon.png
    - assets/icons/monkicon_with_text.png
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png

  #To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
